name: Auto_Coder
on:
  issues:    
    types: [opened, reopened, labeled] 
    
jobs: 
  access_issue_info:  
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest    
    steps:    
      - name: Checkout repository        
        uses: actions/checkout@v4
      
      - name: Debug - List Repo Contents        
        run: ls -R       
      
      - name: Set permissions for  script.sh  
        run: chmod +x scripts/script.sh      
        
      - name: Run  script.sh     
        env:   
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
          REPOSITORY: ${{ github.repository }}        
          ISSUE_NUMBER: ${{ github.event.issue.number }}      
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}     
        run: |          
          ./scripts/script.sh "$GITHUB_TOKEN" "$REPOSITORY" "$ISSUE_NUMBER" "$OPENAI_API_KEY"     
        
      - name: Upload generated files as Artifact       
        uses: actions/upload-artifact@v4        
        with:       
          name: autocoder-artifact          
          path: autocoder-bot/            
      
      - name: Download  artifacts       
        uses: actions/download-artifact@v4        
        with:          
          name: autocoder-artifact          
          path: autocoder-artifact/      
        
      - name: List files in the artifact       
        run: ls -R autocoder-artifact/

      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "autocoder-bot"
          git add .
          git commit -m "Add code snippets from issue #${{ github.event.issue.number }}" -a || echo "No changes to commit"
        shell: bash

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          branch: autocoder-branch-${{ github.event.issue.number }}
          title: "Add code snippets from issue #${{ github.event.issue.number }}"
          body: |
            This pull request adds code snippets from issue #${{ inputs.ISSUE_NUMBER }}.
          labels: "autocoder-bot"
          base: main
          
