name: Say Hello Workflow Name
# trigger
on: 
  issues:
      types: [opened, reopened]
  # Define the event here
jobs:
  handle-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        # actions/checkout
        uses: actions/checkout@v4
      - name: Print Issue Information
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_ASSIGNEES: ${{ join(github.event.issue.assignees.*.login, ', ') }}
          ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}
          
        run: |
          ISSUE_RESPONSE=$(curl -s https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER)
          echo "Issue Number: ${ISSUE_NUMBER}"
          echo "Issue Body: ${ISSUE_BODY}"
          echo "Issue Assignees: ${ISSUE_ASSIGNEES}"
          echo "Issue Labels: ${ISSUE_LABELS}"          
          echo "Issue Information: $ISSUE_RESPONSE"
  

      # - name: Greeting Message
      #   # Write the command here
      #   run: echo "Hello, World"
      
