name: Auto_Coder
on:
  issues:    
    types: [opened, reopened, labeled] 
    
jobs: 
  interact_with_ChatGPT:  
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest    
    steps:    
      - name: Checkout repository        
        uses: "actions/checkout@v4"
        
      - name: Interact with ChatGPT
        id: generated_code
        uses: "tolem/Autocoder@v0.1.0"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          REPOSITORY: ${{ github.repository }} 
          ISSUE_NUMBER: ${{ github.event.issue.number }} 
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
